### PR TITLE
Added Asset directories for Materials, RenderPasses, and RenderTargets

### PR DESCRIPTION
**Pull request by CaptKH**
Test files for JSON loaded materials included.

### CODE REVIEW

**Comment by Honeybunch** [comment]
Looks like some submodule hashes got changed. Can you fix that?

**Comment by CaptKH** [comment]
Not sure if I know how.  Mind explaining?

**Comment by raselneck** [comment]
You pulled the most recent `dev` branch on your machine for all Hatchit submodules, right? Seems like you accidentally added those changes to this PR. ([See here](https://github.com/thirddegree/Hatchit/pull/5/files) and notice Core, Game, Graphics, and Resource have been updated and committed as a part of this PR.)

The easiest way to fix it is to go to your fork, checkout the old hashes (just use the first seven characters, i.e. `git checkout 1234567 && git pull`) and then add, commit, and push those changes. This PR will be auto-updated to include them.

**Comment by Honeybunch** [comment]
This is pretty old. Can I close this?

**Comment by CaptKH** [comment]
Yeah definitely.  Will the directories be added to the Assets folder?

**Pull request closed without merging**
